
version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 3000:3000
    environment:
      APP_NAME: ENC Server
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/mits
      DB_NAME: mits
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}